# Generated by Django 4.2.3 on 2023-08-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_customer_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cust',
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ph_no',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
