# Generated by Django 4.2.4 on 2023-09-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0008_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='custom.webp', null=True, upload_to=''),
        ),
    ]
